### ISSUE TITLE
app:install to generate key?

### ISSUE THREAD

**Issue by jbrooksuk** [GrahamCampbell/Laravel-Core#12]
Would it be a bad idea to have `app:install` also generate the `APP_KEY`?

**Comment by GrahamCampbell** [comment]
Hmmm. D'no. Don't we have an events system Cachet can hook into. I assume this is in the context of cachet?

**Comment by jbrooksuk** [comment]
It's in the context of Cachet. I was going to write it into Cachet, but I figured that since `app:install` makes it sound like the app is being installed (part of that is the key) then Laravel-Core should do it?

**Comment by GrahamCampbell** [comment]
Hmmm. I'll think about it. On the train atm.
